/usr/sbin/named-checkconf /etc/bind/named.conf
/usr/sbin/named-checkzone bac.edu /etc/bind/zones/master/bac.edu.db
/usr/sbin/named-checkzone abbey.bac.edu /etc/bind/zones/master/abbey.bac.edu.db
/usr/sbin/named-checkzone alumni.bac.edu /etc/bind/zones/master/alumni.bac.edu.db
/usr/sbin/named-checkzone pilot.bac.edu /etc/bind/zones/master/pilot.bac.edu.db
/usr/sbin/named-checkzone 184.86.198.in-addr.arpa /etc/bind/zones/master/184.86.198.in-addr.arpa
/usr/sbin/named-checkzone mg.bac.edu /etc/bind/zones/master/other/mg.bac.edu.db
/usr/sbin/named-checkzone 1minutemonk.com /etc/bind/zones/master/other/1minutemonk.com.db
/usr/sbin/named-checkzone oneminutemonk.com /etc/bind/zones/master/other/oneminutemonk.com.db
/usr/sbin/named-checkzone oneminutemonk.net /etc/bind/zones/master/other/oneminutemonk.net.db
/usr/sbin/named-checkzone abbeyhonorsinstitute.com /etc/bind/zones/master/other/abbeyhonorsinstitute.com.db
/usr/sbin/named-checkzone bacadultdegree.com /etc/bind/zones/master/other/bacadultdegree.com.db
/usr/sbin/named-checkzone bacmylife.com /etc/bind/zones/master/other/bacmylife.com.db
/usr/sbin/named-checkzone belmontabbey.org /etc/bind/zones/master/other/belmontabbey.org.db
/usr/sbin/named-checkzone belmontabbeycollege.edu /etc/bind/zones/master/other/belmontabbeycollege.edu.db
/usr/sbin/named-checkzone belmontabbeycollegeadp.com /etc/bind/zones/master/other/belmontabbeycollegeadp.com.db
/usr/sbin/named-checkzone bacroads.com /etc/bind/zones/master/other/bacroads.com.db
/usr/sbin/named-checkzone gotmonks.com /etc/bind/zones/master/other/gotmonks.com.db
/usr/sbin/named-checkzone gotmonks.net /etc/bind/zones/master/other/gotmonks.net.db
/usr/sbin/named-checkzone motorsportmanagement.org /etc/bind/zones/master/other/motorsportmanagement.org.db
/usr/sbin/named-checkzone motorsportmanagement.us /etc/bind/zones/master/other/motorsportmanagement.us.db
/usr/sbin/named-checkzone motorsportprogram.com /etc/bind/zones/master/other/motorsportprogram.com.db
/usr/sbin/named-checkzone motorsportprogram.org /etc/bind/zones/master/other/motorsportprogram.org.db
/usr/sbin/named-checkzone motorsportsdegree.com /etc/bind/zones/master/other/motorsportsdegree.com.db
/usr/sbin/named-checkzone motorsportsdegree.net /etc/bind/zones/master/other/motorsportsdegree.net.db
/usr/sbin/named-checkzone motorsportsdegree.org /etc/bind/zones/master/other/motorsportsdegree.org.db
/usr/sbin/named-checkzone motorsportsmanagement.org /etc/bind/zones/master/other/motorsportsmanagement.org.db
/usr/sbin/named-checkzone motorsportsmanagement.us /etc/bind/zones/master/other/motorsportsmanagement.us.db
/usr/sbin/named-checkzone motorsportsprogram.com /etc/bind/zones/master/other/motorsportsprogram.com.db
/usr/sbin/named-checkzone motorsportsprogram.org /etc/bind/zones/master/other/motorsportsprogram.org.db
/usr/sbin/named-checkzone lessthanaminutetogo.com /etc/bind/zones/master/other/lessthanaminutetogo.com.db
/usr/sbin/named-checkzone reclaimthegame.com /etc/bind/zones/master/other/reclaimthegame.com.db
